### PR TITLE
Implement use gradle plugin for build ndk

### PR DESCRIPTION
**Pull request by skyrylyuk**

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
Can you please explain what this change does?

**Comment by skyrylyuk** [comment]
It changes build native code with help tasks gradle plugin. It simply build script.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. Will it help perhaps to import the project and run it?

**Comment by skyrylyuk** [comment]
Yes, I build project in Android Studio

**Comment by AndroidDeveloperLB** [comment]
I see. Can you please post a step by step tutorial about how to import the project into Android-Studio ? Ever since I've moved to Android-Studio, I couldn't succeed impoting it well.

**Pull request merged**
