### PR TITLE
a simpler way to import the lib.

### PR DESCRIPTION
**Pull request by kcochibili**
described a simpler way to import the lib. and outlined a simple usage example.

### CODE REVIEW

**Comment by njsubedi** [comment]
@AndroidDeveloperLB, you are missing the point. The code will still be available for viewing and editing. You don't always download the source code of everything and compile it yourself do you? Do you compile VLC, or Eclipse, or your OS?

**Comment by AndroidDeveloperLB** [comment]
@njsubedi I don't understand then how to publish it this way.

**Comment by syshex** [comment]
Hi there. 
Making the SO and Jar files available is not missing the point.  Most people do not want to be fiddling about with the native compiler and making awesome changes to the code.... most want to simply use it in the easiest way possible.

Just create a folder at the root and place the compiled SO there, and a JAR for easy usage.

I think my code https://github.com/syshex/android_image_handling was based on yours from some time ago.

**Comment by AndroidDeveloperLB** [comment]
I can't. Sorry.
I failed importing it. I don't have time for this. I hope that some day I will be able to import it easily. I've tried in the past for both Eclispe and Android-Studio. Both took a lot of hours and I've failed in basic import of what I did.
I wanted to add some stuff but I can't.

**Comment by MagneticLlama** [comment]
Hello. I'm working on a Xamarin project that is in need of this library. I've been struggling to get it working, and I wanted to confirm I have a valid aar generated. Does anyone have one available?

**Comment by kcochibili** [comment]
@AndroidDeveloperLB  as you can see, I am not the only one who just wants to use this library without going trough the hassle of compilation. 
I have done this hard work and provided the SO files, so that the next group of people who use your library wont have to. All I asked you was to include the download link I provided in your ReadMe.

If any one wants the so files, here it is http://bit.ly/JNI_BITMAP_SO_FILE

**Comment by AndroidDeveloperLB** [comment]
fine.

**Comment by AndroidDeveloperLB** [comment]
I can't merge it because it has weird conflicts. Please make a new one.

**Pull request closed without merging**
