### PR TITLE
Flip algorithms

### PR DESCRIPTION
**Pull request by rcdvl**
I've added two functions to add flipping sides feature available. Please, check if it's ok for you to merge them in the repo.

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
Great. you are the first one to add features to this library. Thank you.

Can you please put the comments in the code for both the new functions (before and after)  so that whoever uses it will understand ?
I think I know what it does, but it would be better to have it in comments too.
The current comment is a bit weird, or maybe it's not formatted well:

-    /*
-      0 1 2
-      3 4 5  ou 0 1 2 3 4 5 6 7 8 ->
-      6 7 8
-    */

Also, can you please put comments in English and not French? English is the official language, so that all people would understand what's written. I could write in Hebrew too... :)

**Comment by rcdvl** [comment]
I've already removed this weird comment :smile: it's in portuguese BTW... I'll write some javadocs asap

**Comment by AndroidDeveloperLB** [comment]
Thank you. please let me know when it's ready.

**Comment by rcdvl** [comment]
There you go

**Comment by AndroidDeveloperLB** [comment]
Nice. I see you've even updated the sample !
Thank you.

**Pull request merged**
