### PR TITLE
Added gradle config docs

### PR DESCRIPTION
**Pull request by denisk20**

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
Nice, so you've updated the docs, to show how to import to Android-Studio ?

**Comment by denisk20** [comment]
Yes, that's how I managed to import it.

**Comment by AndroidDeveloperLB** [comment]
Thank you. Will try it right away.

**Comment by AndroidDeveloperLB** [comment]
How do I import the project to Android Studio? I've tried using Git-import , but then it tells me "Gradle location is not specified" :

untitled20150110231805

**Comment by AndroidDeveloperLB** [comment]
Now I get this error:
untitled20150110232021

How did you solve those issues? I really hate how Android-Studio handles importing.

**Comment by AndroidDeveloperLB** [comment]
OK, I've done the next steps:
1. download the repository using the zip feature of Github, extract and import as a project.
this actually did step 1+3 for me from your guidelines.
2. I've edited the local.properties and added what you wrote on step 2, and also what you wrote before step 1.

Now I have this issue:
untitled20150110233159

**Comment by denisk20** [comment]
The steps that I've described are valid for someone who already has a valid gradle project and he wants to import the library into it. From what I understand your intention is to import the library project itself into Android Studio so that you could tweak it and run `sample` app to test the results. Currently this is tricky since the project only has partial gradle support (`sample` app is not a gradle project at all). Let me see if I can setup a proper gradle structure to make the process of the import easier.

**Comment by denisk20** [comment]
Please see https://github.com/AndroidDeveloperLB/AndroidJniBitmapOperations/pull/17/

**Pull request merged**
