### PR TITLE
Make changes to the gradle wrapper

### PR DESCRIPTION
**Pull request by palmerc**
After running `gradle wrapper` then `./gradlew assemble` builds the project.

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
Thank you. How did you know what needs to be changed?
Is there a website that show it?

**Comment by AndroidDeveloperLB** [comment]
Now it shows me this error:

Information:Gradle tasks [:JniBitmapOperationsLibrary:compileDebugSources, :sample:compileDebugSources]
WARNING [Project: :JniBitmapOperationsLibrary] Current NDK support is deprecated.  Alternative will be provided in the future.
:JniBitmapOperationsLibrary:buildNative FAILED
Error:Execution failed for task ':JniBitmapOperationsLibrary:buildNative'.
> A problem occurred starting process 'command 'D:\android\ndk/ndk-build''


And that's after I've set "ndk.dir" value on "local.properties" file, to be this way:
    ndk.dir=D:\\android\\ndk

**Comment by palmerc** [comment]
http://stackoverflow.com/questions/23321680/android-studio-ndk-dir-issue <http://stackoverflow.com/questions/23321680/android-studio-ndk-dir-issue>

Did you see this one and escape things correctly?

**Comment by AndroidDeveloperLB** [comment]
Yes, Github removed the double "\" for some reason.

**Comment by palmerc** [comment]
I can see that gradle is causing people a lot of problems so I went ahead and added that gradle update here:

http://stackoverflow.com/questions/25769536/how-when-to-generate-gradle-wrapper-files/27982996#27982996 <http://stackoverflow.com/questions/25769536/how-when-to-generate-gradle-wrapper-files/27982996#27982996>

**Comment by AndroidDeveloperLB** [comment]
I don't understand. What needs to be done? Can you please post a step-by-step guidelines here on the "README.md" file, of how to import the project to Android-Studio ?

**Pull request merged**
